# Generated by Django 3.1.12 on 2023-04-08 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0016_reservation_salle_nombre_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_salle',
            name='chaise_enfant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation_salle',
            name='information_sur_plats',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation_salle',
            name='nombre_personne_adulte',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation_salle',
            name='nombre_personne_enfant',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation_table',
            name='chaise_enfant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation_table',
            name='information_sur_plats',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation_table',
            name='nombre_personne_adulte',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation_table',
            name='nombre_personne_enfant',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation_salle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation_salle',
            name='type_evenement',
            field=models.CharField(choices=[('anniversaire', 'anniversaire'), ('reunion_daffaire', 'reunion_daffaire'), ('Conference', 'Conference'), ('fiançailles', 'fiançailles'), ('Mariage', 'Mariage'), ('autre', 'autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation_table',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation_table',
            name='type_evenement',
            field=models.CharField(choices=[('diner_vip', 'diner_vip'), ('diner_Normal', 'diner_Normal'), ('Conference', 'Conference'), ('reunion_famille', 'reunion_famille'), ('autre', 'autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='salle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
